### PR TITLE
Fixes to allow running under Zope 4 and to ease development

### PR DESCRIPTION
**Pull request by dataflake**

### CODE REVIEW

**Comment by rbu** [comment]
@dataflake Thanks for the PR! Are you using this project as well? Do you think it makes sense to move it to the zopefoundation repo then?

**Comment by dataflake** [comment]
@rbu Thanks for the merge. I have a customer who currently uses Andy Dustman's old ZMySQLDA and MySQLdb1 who will have to move away from it in order to become Python 3-compatible, so I will need a forked product, anyway.

I don't just want to fork and stick it under the Zope Foundation umbrella, it was never an official Zope Foundation project. I wouldn't have a problem with maintaining it as a normal fork either here or under my own ``dataflake`` GitHub handle. Interesting coincidence that you created the fork just a few days before I was thinking of doing the same thing and then saw this.

**Comment by rbu** [comment]
@dataflake Glad we're not alone then. So let's leave the repo here, I've added you as an admin. Feel free to make changes as you would in a Zope Foundation project. We also got control of the PyPI package, should I add you there as well?

**Comment by dataflake** [comment]
That's great, please add me to PyPI. Access for releasing eggs was one of my main worries.

**Pull request merged**
